//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalTransporte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Tiquete = new HashSet<Tiquete>();
        }
    
        public int id_Empleado { get; set; }
        public string nombre_Empleado { get; set; }
        public string email_empleado { get; set; }
        public string password_Empleado { get; set; }
        public Nullable<System.DateTime> fecha_Empleado { get; set; }
        public Nullable<int> idRol_Empleado { get; set; }
        public string Cedula_Empleado { get; set; }
        public string Telefono_Empleado { get; set; }
        public string Direccion_Empleado { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Nit_Empresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tiquete> Tiquete { get; set; }
        public virtual rol rol { get; set; }
    }
}
